title = "Loopring TOML"

[owner]
name = "Loopring corporation"

[order_book]

[log]
    [log.zap_opts]
    level = "debug"
    development = true
    disable_stacktrace = false
    encoding = "console"
    output_paths = ["zap.log", "stderr"]
    error_output_paths = ["err.log"]
        [log.zap_opts.encoder_config]
	    message_key = "msg"
	    level_key = "level"
	    stacktrace_key = "trace"
	    time_key = "ts11111"
	    encode_level = "lowercase"
	    encode_time = "iso8601"

[database]
    server = "localhost"
    port = 8001
    data_dir = "./leveldb"
    name = "leveldb"
    cache_capacity = 8
    buffer_capacity = 4

[ipfs]
    server = "localhost"
    port = 8080
    topic = "test1_topic"

[chain_client]
    raw_url = "http://10.137.107.248:8545"
    [chain_client.senders]
        "0xb5fab0b11776aad5ce60588c16bd59dcfd61a1c2" = "0xfa9a051f7919ec415d9d2a7c729ef4b4762c6ab57efd4b9fcedcb509518b173d"
        "0x48ff2269e58a373120FFdBBdEE3FBceA854AC30A" = "0xec1da652e6e40648c6b474e706d7fe09091fb775a38cef706d603c250db5d872"
        [chain_client.eth]
            gas_price = 10000
            gas_limit = 10000

[common]
    loopringImpAddresses = ["0xd02d3e40cde61c267a3886f5828e03aa4914073d"]
    filter_topics = ["order_filled", "order_cancelled", "ring_mined", "cut_off_timestamp_changed"]
    default_block_number = 4692
    end_block_number = 100000000000000
    develop = true

[miner]
    ringMaxLength = 4
    feeRecepient = "0xe1D2a6B89dABEfC032bF03b239a38aDe2972240E" #0x11a22b9b094422fef93eb6d37d3e6f7809d32e6965865bb403eaa6489a532d9d
    miner = "0xfa9a051f7919ec415d9d2a7c729ef4b4762c6ab57efd4b9fcedcb509518b173d"
    ifRegistryRingHash = false
    throwIfLrcIsInsuffcient = false
    rate_ratio_cvs_threshold = 1000000000000000

    [miner.rate_provider]
        lrc_address = "0x5132a8ce9a61b13b9cAEcd2261abF95323056423"
        base_url = "https://api.coinmarketcap.com/v1/ticker/%s/?convert=CNY"
        currency = "USD"
            [miner.rate_provider.currencies_map]
            "0x5132a8ce9a61b13b9cAEcd2261abF95323056423" = "Loopring"
